[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' https://cdn.plaid.com https://apis.google.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      font-src 'self' data:;
      connect-src 'self' http://localhost:3001 https://web-production-e0804.up.railway.app https://*.googleapis.com https://*.firebaseapp.com https://*.firebaseio.com https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://*.plaid.com https://cdn.plaid.com;
      frame-src https://*.plaid.com https://*.firebaseapp.com https://*.google.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''
